#!/bin/sh
# Print additional version information for non-release trees.

usage() {
	echo "Usage: $0 [srctree]" >&2
	exit 1
}

cd "${1:-.}" || usage

# Check for git and a git repo.
if head=`git rev-parse --verify HEAD 2>/dev/null`; then
	# Do we have an untagged version?
	if  [ "`git name-rev --tags HEAD`" = "HEAD undefined" ]; then
		printf '%s%s' -g `echo "$head" | cut -c1-8`
	else
		# The head is tagged; use the most recent tag name
		printf '-'
		git show-ref --tags --dereference | grep -B 1 "^$head" | sed -n '$s@^.*/@@p' | tr -d '\n'
	fi

	# Are there uncommitted changes?
	if git diff-files | read dummy; then
		printf '%s' -dirty
	fi
fi
